site_name: nama
repo_url: https://github.com/DallanQ chesworthrm/nama
site_url: https://DallanQ chesworthrm.github.io/nama
site_description: NAme MAtching for personal names
site_author: Dallan Quass and Richard Chesworth
edit_uri: edit/main/docs/
repo_name: DallanQ chesworthrm/nama
copyright: Maintained by <a href="https://DallanQ chesworthrm.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DallanQ chesworthrm/nama
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nama

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
